import 'package:flutter/material.dart';
// ignore: unused_import
// import 'package:firebase_core/firebase_core.dart';
// ignore: unused_import
// import 'package:firebase_auth/firebase_auth.dart'
    // as fb_auth; // Alias for Firebase Auth
// import 'package:supabase_flutter/supabase_flutter.dart';
// import 'package:myfluttertask/TodoScreen.dart';
// ignore: unused_import
import 'package:myfluttertask/AuthScreen.dart';
import 'onboarding.dart';
// ignore: unused_import
// import 'firebase_options.dart'; // Generated by flutterfire CLI

// import 'firebase_options.dart'; // Generated by flutterfire CLI
void main()  {
  // WidgetsFlutterBinding.ensureInitialized();

  // // Initialize Firebase
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // WidgetsFlutterBinding.ensureInitialized();
  // await Supabase.initialize(
  //   url: 'https://lovbyyhyoonfzvuqkfms.supabase.co',
  //   anonKey:
  //       'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdmJ5eWh5b29uZnp2dXFrZm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNzUyNzAsImV4cCI6MjA4MDg1MTI3MH0.1oI8Th2ZOSHsfiHLyU3KIeuOmz4Emhdp7gi33JmP32s',
  // );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: OnBoardingScreen(),
    );
  }
}
